"""Добавлено поле cooking_time для dish

Revision ID: 0302fab1c621
Revises: 3e815593cc1f
Create Date: 2025-12-03 00:02:34.846550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0302fab1c621'
down_revision: Union[str, Sequence[str], None] = '3e815593cc1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('cooking_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'cooking_time')
    # ### end Alembic commands ###
