"""добавлена доп информация о блюде

Revision ID: 3e815593cc1f
Revises: 59ee64cc4e4a
Create Date: 2025-12-02 23:03:39.763623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e815593cc1f'
down_revision: Union[str, Sequence[str], None] = '59ee64cc4e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('protein', sa.Integer(), nullable=True))
    op.add_column('dish', sa.Column('fats', sa.Integer(), nullable=True))
    op.add_column('dish', sa.Column('carbs', sa.Integer(), nullable=True))
    op.add_column('dish', sa.Column('calories', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'calories')
    op.drop_column('dish', 'carbs')
    op.drop_column('dish', 'fats')
    op.drop_column('dish', 'protein')
    # ### end Alembic commands ###
