"""Добавлено поле img

Revision ID: 59ee64cc4e4a
Revises: 983631abf187
Create Date: 2025-11-25 01:53:24.152339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ee64cc4e4a'
down_revision: Union[str, Sequence[str], None] = '983631abf187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'img')
    # ### end Alembic commands ###
