"""В моделе Dish добавлено поле description

Revision ID: 6415cfad7ea3
Revises: bd2de69a78c9
Create Date: 2025-11-24 21:54:34.075503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6415cfad7ea3'
down_revision: Union[str, Sequence[str], None] = 'bd2de69a78c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'description')
    # ### end Alembic commands ###
