"""Изменена связь между блюдом и шагом рецепта, добавлена связь между блюдом и ингредиентом

Revision ID: bd2de69a78c9
Revises: 4909b200e6fd
Create Date: 2025-11-24 19:37:12.857008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd2de69a78c9'
down_revision: Union[str, Sequence[str], None] = '4909b200e6fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish_ingredient_association',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('count', sa.String(), nullable=True),
    sa.Column('dish_id', sa.UUID(), nullable=True),
    sa.Column('ingredient_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dish_recipe_step_association')
    op.add_column('recipe_step', sa.Column('dish_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'recipe_step', 'dish', ['dish_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_step', type_='foreignkey')
    op.drop_column('recipe_step', 'dish_id')
    op.create_table('dish_recipe_step_association',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('dish_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('recipe_step_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], name=op.f('dish_recipe_step_association_dish_id_fkey')),
    sa.ForeignKeyConstraint(['recipe_step_id'], ['recipe_step.id'], name=op.f('dish_recipe_step_association_recipe_step_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dish_recipe_step_association_pkey'))
    )
    op.drop_table('dish_ingredient_association')
    # ### end Alembic commands ###
